"""initial

Revision ID: 459bdcc3e7a7
Revises: 
Create Date: 2025-08-25 23:34:58.203541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '459bdcc3e7a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('status_other', sa.String(length=100), nullable=True),
    sa.Column('experience', sa.String(length=50), nullable=True),
    sa.Column('region', sa.String(length=50), nullable=True),
    sa.Column('region_other', sa.String(length=100), nullable=True),
    sa.Column('cloud_platforms', sa.String(length=200), nullable=True),
    sa.Column('cloud_skills', sa.String(length=200), nullable=True),
    sa.Column('cloud_learning', sa.String(length=200), nullable=True),
    sa.Column('importance', sa.String(length=20), nullable=True),
    sa.Column('importance_reason', sa.Text(), nullable=True),
    sa.Column('agreement', sa.String(length=20), nullable=True),
    sa.Column('agreement_reason', sa.Text(), nullable=True),
    sa.Column('impact', sa.String(length=50), nullable=True),
    sa.Column('impact_reason', sa.Text(), nullable=True),
    sa.Column('usage_frequency', sa.String(length=20), nullable=True),
    sa.Column('usage_reason', sa.Text(), nullable=True),
    sa.Column('mandatory', sa.String(length=20), nullable=True),
    sa.Column('mandatory_reason', sa.Text(), nullable=True),
    sa.Column('edu_adequacy', sa.String(length=20), nullable=True),
    sa.Column('edu_adequacy_reason', sa.Text(), nullable=True),
    sa.Column('edu_improvements', sa.String(length=500), nullable=True),
    sa.Column('edu_improvements_reason', sa.Text(), nullable=True),
    sa.Column('valuable_cloud_skills', sa.Text(), nullable=True),
    sa.Column('university_suggestions', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('response')
    # ### end Alembic commands ###
